export const home = '/'
export const login = '/login'
export const logout = '/logout'
export const createAsset = '/assets/create'
export const editAssetWithVar = '/assets/:assetId/edit'
export const viewAssetWithVar = '/assets/:assetId'
export const admin = '/admin'
export const myAccount = '/my-account'
export const privacyPolicy = '/privacy-policy'
export const signUp = '/sign-up'
export const contributors = '/contributors'
export const unapproved = '/unapproved'

export const viewSpeciesWithVar = '/species/:speciesName'
export const viewSpeciesCategoryWithVar = '/species/:speciesName/:categoryName'
export const viewCategoryWithVar = '/category/:categoryName'

// Outdated routes
export const browseAssets = '/browse'
export const browseTutorials = '/browse/tutorial'
export const browseWithVar = '/browse/:tagName'
